version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_daphne_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  ollama:
    image: ollama/ollama
    container_name: ollama_container
    ports:
      - "11424:11424"